### ISSUE TITLE
object of type \'NoneType\' has no len()

### ISSUE THREAD

**Issue by gauravgola96** [paulfitz/mlsql#1]
Everything works fine with curl.
But when i am using requests.post() in python 
it works for the first time but fails in the second time and so on. 
I have to change the name of the parameter 
```
import requests
url = 'http://localhost:5050'
path = 'bridges.csv'
csv = {'csv' : open(path ,'rb')}
payload = {'debug' : False, 'q' : 'how long is throgs neck'}
r =  requests.post(url = url ,files=csv,data=payload)
r.json() > this works for the first time but fails afterwards 

#Second time failed output
r.text > u'{"base":"bridges_b884af26-ef36-4876-9d01-469044242365","error":"object of type \'NoneType\' has no len()"}\n'
r.status_code > 500

#if i do csv1 = {'csv' : open(path ,'rb')} # CHANGED THE NAME OF csv to csv1(or anyother) it works fine again
r =  requests.post(url = url ,files=csv1,data=payload)


```
Anybody knows the reason?

**Comment by paulfitz** [comment]
I think the problem is with `csv = {'csv' : open(path ,'rb')}`.  This will only read correctly once.  `csv = {'csv' : open(path ,'rb').read()}` works for me, can you try it?

**Comment by gauravgola96** [comment]
> I think the problem is with `csv = {'csv' : open(path ,'rb')}`. This will only read correctly once. `csv = {'csv' : open(path ,'rb').read()}` works for me, can you try it?

It worked
