### ISSUE TITLE
API for SQLova

### ISSUE THREAD

**Issue by Bill-ai** [paulfitz/mlsql#10]
As 5050 port is already ON. How can I send and receive data using postman?

**Comment by gdgovinddaga6** [comment]
You can write a API using flask and requests, by running curl commands with python script. Look into the docker file you can find the port and format to run the API.

Best
Govind Daga

**Comment by paulfitz** [comment]
From Postman, it should suffice to:
 * Make a `POST`.
 * To `http://localhost:5050`.
 * With `Body` containing `form-data`.
 * Where that `form-data` contains a text `q` key with value equal to the text question to ask (e.g. `how long is throgs neck`).
 * And where the `form-data` also contains a `csv` key with a file value (e.g. the `bridges.csv` example in this repo).

The result should look like this:
<img width="968" alt="Screen Shot 2020-01-25 at 4 27 55 PM" src="https://user-images.githubusercontent.com/118367/73127529-b05d5000-3f8f-11ea-8499-b58273ca1961.png">

Good luck!

**Comment by Bill-ai** [comment]
Thanks, it worked!
