### ISSUE TITLE
Converting SQL to Answer

### ISSUE THREAD

**Issue by Bill-ai** [paulfitz/mlsql#11]
Hi,

1. Can you please tell me where you are converting the SQL query to the answer inside the dataset?
2. Can I use your edited predict.py file to generate sql and answers?

Thanks
Bill

**Comment by paulfitz** [comment]
1. For Sqlova, evaluating the answer happens right here https://github.com/paulfitz/sqlova/blob/097cbd6e23b9e54e29d860fe8ea40933b1fecd2d/predict.py#L131 - basically just runs the query in Sqlite.  Some nuances: it uses the outputted query structure that than the SQL directly, and does some tweaking of string cases.  For IRNet, as far as I can tell there is no value prediction, so I don't see a way to pull out an actual answer right now with the released code (I'd be very happy to be corrected on this).
2. Yes, I expect so.
