### ISSUE TITLE
custom csv file returning error in postman

### ISSUE THREAD

**Issue by shambhaviparashar** [paulfitz/mlsql#13]
{
    "error": "'utf-8' codec can't decode byte 0xc9 in position 602: invalid continuation byte"
}

**Comment by shambhaviparashar** [comment]
needed to convert my file to UTF-8 encoding.

**Comment by shambhaviparashar** [comment]
needed to convert my file to UTF-8 encoding.

**Comment by paulfitz** [comment]
Thanks for posting what worked for you @shambhaviparashar.
