### ISSUE TITLE
Error while using mlsql docker

### ISSUE THREAD

**Issue by guptalalit** [paulfitz/mlsql#15]
I used the following as given, however i do not get the expected results. Where do you think is the error, please help.

docker run --name sqlova -d -p 5050:5050 paulfitz/sqlova

\mlsql-master>curl -F "csv=@bridges.csv" -F "q=how long is throgs neck" localhost:5050
curl: (52) Empty reply from server

**Comment by paulfitz** [comment]
Sorry, missed this thread.  If it happens again, or to someone else, please attach the output of `docker logs sqlova` and I may be able to help.
