### ISSUE TITLE
For real industrial application, what strategy to locate the exact table?

### ISSUE THREAD

**Issue by guotong1988** [paulfitz/mlsql#3]
The datasets like WikiSQL is that the table corresponding to question is given.

But in real industrial application, we have 100+ tables for 1 new question.

Thank you!

**Comment by paulfitz** [comment]
Good question - I see you're asking it over on https://github.com/microsoft/IRNet/issues/10 and elsewhere https://github.com/search?q=For+real+industrial+application%2C+what+strategy+to+locate+the+exact+table%3F&type=Issues too. I think methods trained to answer questions on databases with a few tables (like with the spider dataset) are an incremental step toward your use case. How about brute force, run the question against each table, and then try to come up with a way to rank confidence in the result?
