### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by sravaniprakash9** [paulfitz/mlsql#4]
Hi,

How to finetune the model with custom queries, tables in .csv and with SQL queries ?
Thank you in advance.

**Comment by paulfitz** [comment]
Hi @sravaniprakash9, for fine-tuning, look upstream to the training script in https://github.com/naver/sqlova. I contributed utilities there for converting csv tables and plain-text queries to the expected formats.  You'll need a little extra to also include expected SQL output.  The utilities in https://github.com/salesforce/WikiSQL/ may be useful. Good luck!
