### ISSUE TITLE
Running in a local environment

### ISSUE THREAD

**Issue by g1644222** [paulfitz/mlsql#8]
Hi,

How to run in local environment without using docker?

also, I want to import a natural language sentence into a program and get the arithmetic value and the nth value.
Can you tell me how?

Thank you in advance.

**Comment by g1644222** [comment]
> Hi,
> 
> How to run in local environment without using docker?
> Thank you in advance.

**Comment by paulfitz** [comment]
To run without docker, you could follow the steps in https://github.com/paulfitz/mlsql/blob/master/sqlova/Dockerfile.  You'll need to adapt the steps for your OS.

Can you give an example of a natural sentence input and the output you'd like to get from it?  I'm not clear on what the arithmetic value and the nth value mean exactly in this context.

**Comment by g1644222** [comment]
Thank you for your prompt reply!

To explain the example in bridges.csv,
input: which bridge is Second longest bridge
output: Bronx Whitestone

input: How long is the difference between the longest bridge and the shortest bridge?
output: 2313

**Comment by paulfitz** [comment]
Thanks for the explanation. I think that kind of query is currently beyond Sqlova, and I'm not sure if there are many examples like it in the WikiSQL training data (you can get a sense for the kinds of questions the model has been trained on from the 100 examples in the appendix of https://arxiv.org/pdf/1902.01069v1.pdf).

**Comment by Bill-ai** [comment]
I'm sorry, I don't get how to decode the Docker File, can you please help me run in the local. Please help.

Thanks
Bill

**Comment by g1644222** [comment]
@paulfitz 
thank you for answering! !
I will ask sqlova.

@Bill-ai 
What do you not know?
