### ISSUE TITLE
Not working on custom data?

### ISSUE THREAD

**Issue by gdgovinddaga6** [paulfitz/mlsql#9]
I have implemented it and used it and now I can get all the answers, but when I try the same on my custom csv file, it generates the query but doesn't "answer" for the query as it did to your csv files. May I know the reason?
and What is this params thing? I don't understand why not keeps the params in the query?

**Comment by paulfitz** [comment]
@gdgovinddaga6 would you be willing to post your csv file, or some small part of it that is sufficient to show the problem?  Are you not getting no answer at all, or a wrong answer?  Hard to say why in general.  Sqlova is trained on the WikiSQL dataset, IRNet is trained on the Spider dataset.  Tables or questions that are very different than what is in those datasets could easily result in failures.

It is common practice to factor out values (particularly strings) from a query and supply them separately as bind parameters.  This helps avoid problems with strings with special characters getting interpreted as sql.  If you talk to a database via a library in a language like python or javascript, the library will have support for this and encourage you to do so.  It is a bit awkward if you are pasting the queries straight into a database client though, I admit.

**Comment by gdgovinddaga6** [comment]
Thanks for the quick reply, I figured it out myself. The issue was with the CSV file where a col name was missing.
